//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SumbittedDataHeader
    {
        public long TSDHID { get; set; }
        public string FileName { get; set; }
        public string AppID { get; set; }
        public string EntityName { get; set; }
        public int TotalCount { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int ManadateStatus { get; set; }
        public Nullable<bool> IsEMandate { get; set; }
        public string UtilityCode { get; set; }
    }
}
