//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubmittedDataDetails
    {
        public long TSDDID { get; set; }
        public Nullable<long> TSDHID { get; set; }
        public Nullable<bool> IsExcelMandateDownload { get; set; }
        public Nullable<bool> IsSnapMandateDownload { get; set; }
        public Nullable<bool> IsMobileData { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsScan { get; set; }
        public string JPGPath { get; set; }
        public string TIPPath { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<long> mandateid { get; set; }
        public string BankName { get; set; }
        public string Amount { get; set; }
        public string Code { get; set; }
        public string BankName1 { get; set; }
        public Nullable<System.DateTime> DateOnMandate { get; set; }
        public string AcNo { get; set; }
        public string Refrence1 { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public string Customer1 { get; set; }
        public string debittype { get; set; }
        public string Frequency { get; set; }
        public string ToDebit { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string NPCIRejectReason { get; set; }
        public string UMRN { get; set; }
        public string MandateStatus { get; set; }
        public string ErrorCode { get; set; }
        public Nullable<long> StatusId { get; set; }
        public string NPCIMsgId { get; set; }
        public bool IsEMandate { get; set; }
        public string MessageID { get; set; }
        public string AcceptRefNo { get; set; }
    }
}
