//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AllDatabaseName
    {
        public int TADNID { get; set; }
        public string AppID { get; set; }
        public string PathOut { get; set; }
        public string PathProcess { get; set; }
        public Nullable<int> Did { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string EntityName { get; set; }
        public string PathEmandateOut { get; set; }
        public string PathEmandateProcessed { get; set; }
        public string PathPresOut { get; set; }
        public string PathPresProcessed { get; set; }
        public bool IsLinkServer { get; set; }
        public string UtilityCode { get; set; }
    }
}
