//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAlertNotification
    {
        public long NotificationID { get; set; }
        public int LinkID { get; set; }
        public string NotificationMsg { get; set; }
        public bool IsShown { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Createdon { get; set; }
        public int CreatedBy { get; set; }
        public int EntityID { get; set; }
        public int CreatedFor { get; set; }
    }
}
