//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankEntityOnBoarding
    {
        public long BankEntityOnboardingId { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public Nullable<bool> IsSubsidaryBank { get; set; }
        public string IsSubsidaryParentBankName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string HOAddress { get; set; }
        public string HOCountry { get; set; }
        public string HOState { get; set; }
        public string HOCity { get; set; }
        public string HOPincode { get; set; }
        public string HORegionCode { get; set; }
        public string PHOAddress { get; set; }
        public string PHOCountry { get; set; }
        public string PHOState { get; set; }
        public string PHOCity { get; set; }
        public string PHOPincode { get; set; }
        public string PHORegionCode { get; set; }
        public string StructureContries { get; set; }
        public string DomesticBranchTimeBoarding { get; set; }
        public string OverSeasBranchTimeBoarding { get; set; }
        public string HomeSupervisoryAuthority { get; set; }
        public string DetailsOfSupervisoryArrangements { get; set; }
        public Nullable<bool> NachPhysicalMandate { get; set; }
        public Nullable<bool> NachPhysicalFrontRequired { get; set; }
        public Nullable<bool> NachEmandate { get; set; }
        public Nullable<bool> NachEmandateFrontRequired { get; set; }
        public Nullable<bool> NachDirectDebit { get; set; }
        public Nullable<bool> NachDirectDebitFrontRequired { get; set; }
        public Nullable<bool> NachAdharBasMandate { get; set; }
        public Nullable<bool> NachAdharBasFrontRequired { get; set; }
        public Nullable<bool> CollectionNachTranPresentation { get; set; }
        public Nullable<bool> CollectionNachTranPresentationFrontRequired { get; set; }
        public Nullable<bool> UPICollection { get; set; }
        public Nullable<bool> UPICollectionFrontRequired { get; set; }
        public Nullable<bool> BBPSCollection { get; set; }
        public Nullable<bool> BBPSCollectionFrontRequired { get; set; }
        public Nullable<bool> APBSCollection { get; set; }
        public Nullable<bool> APBSFrontRequired { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
