//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankMaster
    {
        public long BankMasterId { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string Frequency { get; set; }
        public string Guidlines { get; set; }
        public bool NPCIStatus { get; set; }
        public string AccountValidation { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string NetBanking { get; set; }
        public string DebitCard { get; set; }
    }
}
