//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorpOnBoardingBillingDetail
    {
        public long TCOBBDId { get; set; }
        public long TCEDID { get; set; }
        public string BillingContactPerson { get; set; }
        public string BillingDesignation { get; set; }
        public string BillingContactNo { get; set; }
        public string BillingFaxNo { get; set; }
        public string BillingAddress { get; set; }
        public string PickupContactPerson { get; set; }
        public string PickupLocationAddress { get; set; }
        public Nullable<int> ArrangmentDays { get; set; }
        public string CommuMail_Primary { get; set; }
        public string CommuMail_Billing { get; set; }
        public string ChargeDebitAccNo { get; set; }
        public string BankCorpID { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public string IFSC { get; set; }
        public Nullable<long> Settlement { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<long> AppId { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
