//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorporateOnBoardingServicesCharge
    {
        public long TSOID { get; set; }
        public long TCEDID { get; set; }
        public Nullable<decimal> PerTransCharge { get; set; }
        public Nullable<decimal> Setup_IntegrationCharge { get; set; }
        public Nullable<decimal> UserIdChargePerMonth { get; set; }
        public Nullable<decimal> TrainingCharge { get; set; }
        public Nullable<decimal> AnnualMaintenance { get; set; }
        public Nullable<bool> IsPhysicalMandate { get; set; }
        public Nullable<bool> IsEMandate { get; set; }
        public Nullable<bool> IsDirectDebitMandate { get; set; }
        public Nullable<bool> IsAadharBasedMandate { get; set; }
        public Nullable<bool> IsNACHTransPresent { get; set; }
        public Nullable<bool> IsUPICollection { get; set; }
        public Nullable<bool> IsBBPS { get; set; }
        public Nullable<bool> IsAPBS { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string AppId { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
