//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorporateFinancialDetail
    {
        public long TCFDID { get; set; }
        public Nullable<long> TCEDID { get; set; }
        public string PAN { get; set; }
        public string TAN { get; set; }
        public string GST { get; set; }
        public Nullable<int> AccountHoldingRegionalMember { get; set; }
        public Nullable<int> AccuntHoldingPSM { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
