//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorporateRequest
    {
        public long ReqID { get; set; }
        public string RequestNo { get; set; }
        public Nullable<int> RequestType { get; set; }
        public string CorporateName { get; set; }
        public Nullable<bool> IsPhysical { get; set; }
        public Nullable<bool> IsEmandate { get; set; }
        public Nullable<bool> IsDebitPresentation { get; set; }
        public Nullable<bool> IsAccountValidation { get; set; }
        public Nullable<bool> IsAPiIntegration { get; set; }
        public Nullable<bool> Isaadharbasevalidation { get; set; }
        public string PrimaryName { get; set; }
        public string PrimaryEmail { get; set; }
        public Nullable<long> PrimaryPhoneno { get; set; }
        public string PrimaryAddress { get; set; }
        public string Emandateemail { get; set; }
        public Nullable<long> EmandatePhone { get; set; }
        public string MandateAttchment { get; set; }
        public string UploadLogo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<int> IsRequestStatus { get; set; }
        public string AppId { get; set; }
        public Nullable<bool> IsRequestReject { get; set; }
        public string RejectReason { get; set; }
    }
}
