//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityPrimaryEmandateDetail
    {
        public long EPEDId { get; set; }
        public string PrimaryName { get; set; }
        public string PrimaryEmail { get; set; }
        public string PrimaryPhoneNo { get; set; }
        public string PrimaryAddress { get; set; }
        public string EmandateEmail { get; set; }
        public string EmandatePhoneNo { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
