//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityAccountvalParameter
    {
        public long AccountvalParamId { get; set; }
        public Nullable<int> MaxValidationperMandate { get; set; }
        public Nullable<int> MaxValidationperRef { get; set; }
        public Nullable<int> MaxValidationperAccount { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> ProductId { get; set; }
    }
}
