//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIssueHeader
    {
        public long IssueId { get; set; }
        public string RequestNo { get; set; }
        public Nullable<long> ModuleId { get; set; }
        public Nullable<long> SubModuleId { get; set; }
        public Nullable<long> Priority { get; set; }
        public string IssueDetails { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string IssueAttachementPath { get; set; }
    }
}
