//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImageActivityDetail
    {
        public int ImageActivityDetId { get; set; }
        public long ImageActivityId { get; set; }
        public string FileName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<long> MandateId { get; set; }
        public Nullable<bool> IsMapped { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsReverse { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<bool> IsCancel { get; set; }
    }
}
