//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmandatebankbulkuploadhistory_15sept2020
    {
        public int Sno { get; set; }
        public Nullable<long> ActivityId { get; set; }
        public string MandateId { get; set; }
        public string DateonMandate { get; set; }
        public string SponsorBank { get; set; }
        public string Utilitycode { get; set; }
        public string IWehereby { get; set; }
        public string ToDebit { get; set; }
        public string BankacNumber { get; set; }
        public string BankName { get; set; }
        public string IFSC { get; set; }
        public string OrMICR { get; set; }
        public string Amount { get; set; }
        public string Frequency { get; set; }
        public string DebitType { get; set; }
        public string RefNo1 { get; set; }
        public string RefNo2 { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailID { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string NameAsBankRrds1 { get; set; }
        public string NameAsBankRrds2 { get; set; }
        public string NameAsBankRrds3 { get; set; }
        public Nullable<long> ULUID { get; set; }
        public string CategoryCode { get; set; }
        public string entityId { get; set; }
        public string blank { get; set; }
        public string UserId { get; set; }
        public string CreatedOn { get; set; }
        public string Remark { get; set; }
        public string UMRN { get; set; }
    }
}
