//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPresentment_ExlUploadDataDetail
    {
        public long TEUDID { get; set; }
        public long TEUHID { get; set; }
        public string UMRN { get; set; }
        public string RefrenceNo { get; set; }
        public decimal Amount { get; set; }
        public bool IsUMRN_Val { get; set; }
        public bool IsAmount_Val { get; set; }
        public bool IsDate_Val { get; set; }
        public long Trans { get; set; }
    }
}
