//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhysicalRequestHeader
    {
        public long PhysicalHeaderId { get; set; }
        public Nullable<long> AppId { get; set; }
        public string CorporateName { get; set; }
        public string CorporateNumber { get; set; }
        public Nullable<long> ToTalRecords { get; set; }
        public string UtilityCode { get; set; }
        public Nullable<long> DownloadCount { get; set; }
        public Nullable<long> Downloadby { get; set; }
        public Nullable<System.DateTime> DownloadON { get; set; }
        public Nullable<long> UMRNReceiveCount { get; set; }
        public Nullable<long> FinalStatusCount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> SubmitToBankDate { get; set; }
        public string Slot { get; set; }
    }
}
