//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPresentment_ExlUploadDataHeader
    {
        public long TEUHID { get; set; }
        public string ActivityName { get; set; }
        public Nullable<int> EntityID { get; set; }
        public Nullable<long> TotalUpload { get; set; }
        public Nullable<long> TotalProcess { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string BankName { get; set; }
        public string Date { get; set; }
        public Nullable<long> TransheaderId { get; set; }
        public string SponsorbankId { get; set; }
        public string ClientCode { get; set; }
        public string CorporateAcNo { get; set; }
    }
}
